### PR TITLE
Insertion & Merge Sort

### PR DESCRIPTION
**Pull request by Alok5445Sagar**
I have added the code for Selection Sort, Insertion Sort and Merge Sort in C++. Please have a look into it and merge the pull req.

### CODE REVIEW

**Review by abhiramkg2000 — COMMENTED** [review]
please change the file name of "SelectionSort copy" to MergeSort.

**Comment by Alok5445Sagar** [comment]
Done the changes, Please have a look and merge the pr.

**Comment by Alok5445Sagar** [comment]
And it is showing in my Hackoctoberfest profile that your repo is not currently participating in hackoctober 2022, pls have a look into it too.

**Comment by abhiramkg2000** [comment]
@Alok5445Sagar  please star the repository

**Pull request merged**
