### PR TITLE
Added Maximum Path Sum Leetcode - HackterFest2022

### PR DESCRIPTION
**Pull request by SubratYeeshu**
Please merge my pull request under hacktoberfest2022 label  @abhiramkg2000  Sir

### CODE REVIEW

**Review by abhiramkg2000 — COMMENTED** [review]
@SubratYeeshu can you explain why u added ".vscode/settings.json" file

**Comment by SubratYeeshu** [comment]
it is just some settings of vscode by default, it is pushed automatically whenever pull request is made from vscode

**Comment by SubratYeeshu** [comment]
i will delete it when i will pull again next time

**Comment by abhiramkg2000** [comment]
@SubratYeeshu  please delete that folder and create another pull request.

**Pull request merged**
